// src/app/layout.js

// 1. Import better fon
import "./globals.css";

import { Manrope, Parisienne, Anton } from "next/font/google";

const anton = Anton({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-title",
});

// 2. Configure them
const manrope = Manrope({
  subsets: ["latin"],
  display: "swap",
  // Define the CSS variable name
  variable: "--font-primary",
});

// A much more elegant script font than standard options
const parisienne = Parisienne({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-signature",
});

export const metadata = {
  title: "Vikas Gautam | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* 3. Add variables to the body class so Tailwind can see them */}
      <body className={`${manrope.variable} ${parisienne.variable} ${anton.variable} bg-background text-white antialiased`}>
        <div id="modal-root"></div>

        {children}
      </body>
    </html>
  );
}