export const skills = [
  { name: "JavaScript", image: "/skills/js.svg", category: "Frontend", description: "The dynamic language of the web." },
  { name: "TypeScript", image: "/skills/ts.svg", category: "Frontend", description: "JavaScript with robust static typing." },
  { name: "React", image: "/skills/react.svg", category: "Frontend", description: "A powerful library for building UIs." },
  { name: "Next.js", image: "/skills/next.svg", category: "Frontend", description: "The leading React framework for production." },
  { name: "Tailwind CSS", image: "/skills/Tailwind.svg", category: "Frontend", description: "Utility-first CSS framework for rapid UI development." },
  { name: "WebRTC", image: "/skills/webrtc.svg", category: "Frontend", description: "Real-time communication for audio, video, and data." },

  { name: "Node.js", image: "/skills/nodejs.svg", category: "Backend", description: "JavaScript runtime for building servers." },
  { name: "FastAPI", image: "/skills/Fastapi.svg", category: "Backend", description: "High-performance Python framework for APIs." },
  { name: "Prisma", image: "/skills/prisma.svg", category: "Backend", description: "Next-gen ORM for Node.js & TypeScript." },
  { name: "PostgreSQL", image: "/skills/postgresql.svg", category: "Backend", description: "A powerful, open-source relational database." },
  { name: "MongoDB", image: "/skills/mongo.svg", category: "Backend", description: "Popular NoSQL document database." },
  { name: "MySQL", image: "/skills/mysql.svg", category: "Backend", description: "The world's most popular open-source database." },
  { name: "Supabase", image: "/skills/supabase.svg", category: "Backend", description: "Firebase alternative built on PostgreSQL." },
  { name: "MCP Servers", image: "/skills/mcp.svg", category: "Backend", description: "Modular, tool-based server architecture for LLMs." },

  { name: "Golang", image: "/skills/golang.svg", category: "Languages", description: "A language known for simplicity and speed." },
  { name: "Python", image: "/skills/python.svg", category: "Languages", description: "Versatile language for web, data & AI." },
  { name: "C++", image: "/skills/c.svg", category: "Languages", description: "High-performance systems language." },
  { name: "Java", image: "/skills/java.svg", category: "Languages", description: "Class-based, object-oriented language." },

  { name: "Docker", image: "/skills/docker.svg", category: "DevOps", description: "Platform for containerizing applications." },
  { name: "NGINX", image: "/skills/NGINX.svg", category: "DevOps", description: "High-performance web server & reverse proxy." },
  { name: "Vercel", image: "/skills/vercel.svg", category: "DevOps", description: "Cloud platform optimized for the frontend." },
  { name: "Render", image: "/skills/render.svg", category: "DevOps", description: "Unified cloud for apps and web services." },
  { name: "Railway", image: "/skills/railway.svg", category: "DevOps", description: "Infrastructure platform for developers." },
  { name: "Postman", image: "/skills/Postman.svg", category: "DevOps", description: "API testing & collaboration platform." },

  { name: "Gemini API", image: "/skills/gemini.svg", category: "AI", description: "Access Google's powerful generative models." },
  { name: "Groq API", image: "/skills/groq.svg", category: "AI", description: "High-speed inference API for running LLMs blazingly fast." },
  { name: "Llama 3 API", image: "/skills/llama.svg", category: "AI", description: "Meta's powerful open-source LLM family." },
  { name: "SerpApi", image: "/skills/serp.png", category: "AI", description: "Real-time Google Search API for data extraction." },
  { name: "LangChain", image: "/skills/langchain.svg", category: "AI", description: "Framework for developing LLM applications." },
  { name: "LangGraph", image: "/skills/langgraph.svg", category: "AI", description: "Graph-based framework for building agentic workflows." },
  { name: "Ollama", image: "/skills/ollama.svg", category: "AI", description: "Run and manage local LLMs easily." },
  { name: "Prompt Engineering", image: "/skills/prompt.svg", category: "AI", description: "Crafting effective inputs for AI models." },
  { name: "spaCy", image: "/skills/Spacy.svg", category: "AI", description: "Industrial-strength NLP library." },
  { name: "Pandas", image: "/skills/Pandas.svg", category: "AI", description: "Powerful data analysis and manipulation library." },
  { name: "NumPy", image: "/skills/numpy.svg", category: "AI", description: "Fundamental package for numerical computing in Python." },
  { name: "Matplotlib", image: "/skills/matplotlib.svg", category: "AI", description: "2D plotting library for Python & data visualization." },
  { name: "Dialogflow", image: "/skills/dialogflow.svg", category: "AI", description: "Build conversational AI experiences." },
  { name: "Streamlit", image: "/skills/Streamlit.svg", category: "AI", description: "Build and share data apps, fast." },
];